export default [
  {
    type: 'video',
    text: '视频',
    format: [
      'mp4',
      'flv',
      'asf',
      'rm',
      'rmvb',
      'mpeg',
      'mov',
      'avi',
      'flash',
      'mpegts',
      'm4s',
      'm3u8',
      'matroska',
      'hls',
      'quicktime',
      'webm',
    ],
    maxSize: 524288000,
    fileType: 'media',
  },
  {
    type: 'audio',
    text: '音频',
    format: ['mp3', 'm4a', 'wav', 'wma', 'amr', 'aac'],
    maxSize: 52428800,
    fileType: 'media',
  },
  { type: 'image', text: '图片', format: ['png', 'jpg', 'jpeg'], maxSize: 52428800, fileType: 'image' },
  { type: 'dynamic_img', text: '动图', format: ['gif', 'webp'], maxSize: 52428800, fileType: 'image' },
  { type: 'subtitle', text: '字幕', format: ['srt', 'vtt', 'ass'], maxSize: 52428800, fileType: 'object' },
  { type: 'font', text: '字体', format: ['ttf', 'fon', 'ttc'], maxSize: 52428800, fileType: 'object' },
];
