const forms = require("@tailwindcss/forms");
const containerQueries = require("@tailwindcss/container-queries");

module.exports = {
  content: [
    "./public/workspace.html",
    "./public/main.js",
    "./public/modules/**/*.js",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#ECEFF1",
        "inverse-primary": "#CFD8DC",
        "tertiary-container": "#CFD8DC",
        "on-secondary-container": "#2C3E50",
        "on-primary-container": "#0B1320",
        "tertiary-fixed": "#CFD8DC",
        "primary-container": "#CFD8DC",
        "surface-container": "#CFD8DC",
        "error-container": "#fe8983",
        "surface-container-low": "#ECEFF1",
        "primary-fixed": "#CFD8DC",
        "on-secondary": "#ECEFF1",
        "surface-tint": "#0B1320",
        "on-surface-variant": "#2C3E50",
        "primary-fixed-dim": "#90A4AE",
        "surface-bright": "#ECEFF1",
        "on-background": "#0B1320",
        "surface-dim": "#CFD8DC",
        "on-secondary-fixed-variant": "#2C3E50",
        "surface-container-lowest": "#ffffff",
        "on-error": "#fff7f6",
        "on-tertiary-fixed-variant": "#2C3E50",
        "error-dim": "#4e0309",
        "inverse-surface": "#0B1320",
        "on-primary": "#ECEFF1",
        "secondary-container": "#CFD8DC",
        "primary-dim": "#2C3E50",
        "on-secondary-fixed": "#0B1320",
        "tertiary": "#2C3E50",
        "surface-container-highest": "#CFD8DC",
        "secondary-dim": "#2C3E50",
        "tertiary-dim": "#2C3E50",
        "on-primary-fixed-variant": "#0B1320",
        "on-primary-fixed": "#0B1320",
        "on-error-container": "#752121",
        "on-tertiary-container": "#2C3E50",
        "surface-container-high": "#CFD8DC",
        "outline-variant": "#90A4AE",
        "on-tertiary-fixed": "#0B1320",
        "outline": "#90A4AE",
        "error": "#9f403d",
        "background": "#ECEFF1",
        "primary": "#0B1320",
        "inverse-on-surface": "#90A4AE",
        "secondary": "#2C3E50",
        "on-tertiary": "#ECEFF1",
        "surface-variant": "#CFD8DC",
        "secondary-fixed-dim": "#90A4AE",
        "tertiary-fixed-dim": "#90A4AE",
        "on-surface": "#0B1320",
        "secondary-fixed": "#CFD8DC",
      },
      borderRadius: { DEFAULT: "1rem", lg: "2rem", xl: "3rem", full: "9999px" },
      fontFamily: { headline: ["Inter"], body: ["Inter"], label: ["Inter"] },
    },
  },
  plugins: [forms, containerQueries],
};
