export const TOOLBOX_IMAGE_GENERATION_MAX_COUNT = 4;
export const TOOLBOX_IMAGE_REFERENCE_MAX_COUNT = 1;
export const TOOLBOX_VIDEO_RUNNING_LIMIT = 3;
export const TOOLBOX_HISTORY_DEFAULT_LIMIT = 30;
export const TOOLBOX_HISTORY_MAX_LIMIT = 100;
