module.exports = {
  apps: [
    {
      name: 'origin-web',
      cwd: process.env.ORIGIN_APP_DIR || '/opt/origin',
      script: 'npm',
      args: 'run start',
      exec_mode: 'fork',
      instances: 1,
      env: {
        NODE_ENV: 'production',
        PORT: process.env.PORT || '3000',
        ORIGIN_ENV_FILE: process.env.ORIGIN_ENV_FILE || '/etc/origin/origin.env',
        ORIGIN_PROCESS_ROLE: 'web',
        ORIGIN_BATCH_INLINE_RUNNER: '0',
        ORIGIN_INLINE_ONLINE_EDITOR_DOWNLOAD: '0',
        ORIGIN_REAP_ORPHANS_ON_START: '0',
        ORIGIN_EXPECT_WORKER: '1',
      },
      max_restarts: 20,
      min_uptime: '20s',
      kill_timeout: 60000,
      exp_backoff_restart_delay: 2000,
    },
    {
      name: 'origin-worker',
      cwd: process.env.ORIGIN_APP_DIR || '/opt/origin',
      script: 'npm',
      args: 'run worker',
      exec_mode: 'fork',
      instances: 1,
      env: {
        NODE_ENV: 'production',
        ORIGIN_ENV_FILE: process.env.ORIGIN_ENV_FILE || '/etc/origin/origin.env',
        ORIGIN_PROCESS_ROLE: 'worker',
        ORIGIN_BATCH_RECOVERY_ENABLED: '1',
        ORIGIN_REAP_ORPHANS_ON_START: '0',
        ORIGIN_INLINE_ONLINE_EDITOR_DOWNLOAD: '1',
        ORIGIN_DEFER_SEEDANCE_PROVIDER_POLLING: '1',
        ORIGIN_PROVIDER_POLLING_INTERVAL_MS: process.env.ORIGIN_PROVIDER_POLLING_INTERVAL_MS || '10000',
        ORIGIN_PROVIDER_POLLING_LIMIT: process.env.ORIGIN_PROVIDER_POLLING_LIMIT || '10',
      },
      max_restarts: 20,
      min_uptime: '20s',
      kill_timeout: 60000,
      exp_backoff_restart_delay: 2000,
    },
  ],
};
